# Generated by Django 3.2.9 on 2021-11-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeIncApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='installation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'managed': False},
        ),
    ]
