# Generated by Django 3.2.9 on 2021-11-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeIncApp', '0003_auto_20211112_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
    ]
