# Generated by Django 3.2.9 on 2021-11-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeIncApp', '0004_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
    ]
